FROM node:10-alpine

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY package*.json ./

USER node

RUN npm install

COPY --chown=node:node . .


# ENV Variables
ARG MONGODB_URL
ARG PAYSTACK_SECRET
ARG JWT_SECRET
ARG JWT_ACCESS_EXPIRATION_MINUTES
ARG JWT_REFRESH_EXPIRATION_DAYS
ARG JWT_RESET_PASSWORD_EXPIRATION_MINUTES
ARG JWT_VERIFY_EMAIL_EXPIRATION_MINUTES
ARG NODE_ENV
ARG PORT
ARG CLIENT_URL
ARG SMTP_HOST
ARG SMTP_PORT
ARG SMTP_USERNAME
ARG SMTP_PASSWORD
ARG SMTP_FROM
ARG SMTP_TPL_PATH=templates

ENV MONGODB_URL=$MONGODB_URL
ENV PAYSTACK_SECRET=$PAYSTACK_SECRET
ENV JWT_SECRET=$JWT_SECRET
ENV JWT_ACCESS_EXPIRATION_MINUTES=$JWT_ACCESS_EXPIRATION_MINUTES
ENV JWT_REFRESH_EXPIRATION_DAYS=$JWT_REFRESH_EXPIRATION_DAYS
ENV JWT_RESET_PASSWORD_EXPIRATION_MINUTES=$JWT_RESET_PASSWORD_EXPIRATION_MINUTES
ENV JWT_VERIFY_EMAIL_EXPIRATION_MINUTES=$JWT_VERIFY_EMAIL_EXPIRATION_MINUTES
ENV NODE_ENV=$NODE_ENV
ENV PORT=$PORT
ENV CLIENT_URL=$CLIENT_URL
ENV SMTP_HOST=$SMTP_HOST
ENV SMTP_PORT=$SMTP_PORT
ENV SMTP_USERNAME=$SMTP_USERNAME
ENV SMTP_PASSWORD=$SMTP_PASSWORD
ENV SMTP_FROM=$SMTP_FROM
ENV SMTP_TPL_PATH=templates

EXPOSE 8000

# Copy the start script
COPY start.sh .

# Make the start script executable
RUN chmod +x start.sh